

import Foundation
import SwiftUI

class AppData
{
    static let instance = AppData()
    init () {}
    
    
    
    let searchFilter = SearchFilter(name: "Default", imageName: "arrow.clockwise.circle.fill")
    
    
    
    
    let tempSvgs: [MySvg] = [
        MySvg(fileName: "calendar",
              thumbName: "calendar",
              author: "John Doe",
              tags: ["Great", "Red", "Weird"],
              rating: 5.24,
              uploadDate: Calendar.current.date(byAdding: .day, value: -7, to: Date())!), // For testing: Set the upload date to 7 days ago),
        MySvg(fileName: "acuarium",
              thumbName: "acuarium",
              author: "Jane Smith",
              tags: ["Awesome", "Blue", "Fun"],
              rating: 1.91,
              uploadDate: Date()),
        MySvg(fileName: "android",
              thumbName: "android",
              author: "Alex Johnson",
              tags: ["Creative", "Yellow", "Exciting"],
              rating: 9.13,
              uploadDate: Date()),
        MySvg(fileName: "bell",
              thumbName: "bell",
              author: "David Wilson",
              tags: ["Amazing", "Green", "Cool"],
              rating: 8.70,
              uploadDate: Date()),
        MySvg(fileName: "birthday-cake",
              thumbName: "birthday-cake",
              author: "Emily Brown",
              tags: ["Fantastic", "Purple", "Innovative"],
              rating: 8.18,
              uploadDate: Date()),
        MySvg(fileName: "butterfly",
              thumbName: "butterfly",
              author: "Michael Davis",
              tags: ["Epic", "Orange", "Unique"],
              rating: 6.87,
              uploadDate: Date()),
        MySvg(fileName: "camp",
              thumbName: "camp",
              author: "Olivia Taylor",
              tags: ["Excellent", "Pink", "Adventurous"],
              rating: 8.42,
              uploadDate: Date()),
        MySvg(fileName: "chat",
              thumbName: "chat",
              author: "Daniel Anderson",
              tags: ["Brilliant", "Teal", "Inspiring"],
              rating: 5.48,
              uploadDate: Date()),
        MySvg(fileName: "cow",
              thumbName: "cow",
              author: "Sophia Clark",
              tags: ["Magical", "Silver", "Mysterious"],
              rating: 8.35,
              uploadDate: Date()),
        MySvg(fileName: "diamond",
              thumbName: "diamond",
              author: "Matthew Martinez",
              tags: ["Spectacular", "Gold", "Energetic"],
              rating: 4.06,
              uploadDate: Date()),
        MySvg(fileName: "duck",
              thumbName: "duck",
              author: "Abigail Thompson",
              tags: ["Marvelous", "Cyan", "Vibrant"],
              rating: 9.58,
              uploadDate: Date()),
        MySvg(fileName: "employeebank",
              thumbName: "employeebank",
              author: "Jacob White",
              tags: ["Wonderful", "Lime", "Playful"],
              rating: 0.84,
              uploadDate: Date()),
        MySvg(fileName: "firecamp",
              thumbName: "firecamp",
              author: "Mia Lee",
              tags: ["Terrific", "Indigo", "Dynamic"],
              rating: 8.61,
              uploadDate: Date()),
        MySvg(fileName: "flower-bouquet",
              thumbName: "flower-bouquet",
              author: "Ethan Lewis",
              tags: ["Phenomenal", "Amber", "Captivating"],
              rating: 2.97,
              uploadDate: Date()),
        MySvg(fileName: "fox",
              thumbName: "fox",
              author: "Charlotte Turner",
              tags: ["Outstanding", "Turquoise", "Imaginative"],
              rating: 9.95,
              uploadDate: Date()),
        MySvg(fileName: "frog",
              thumbName: "frog",
              author: "William Walker",
              tags: ["Impressive", "Magenta", "Whimsical"],
              rating: 8.31,
              uploadDate: Date()),
        MySvg(fileName: "gift",
              thumbName: "gift",
              author: "Ava Rodriguez",
              tags: ["Stunning", "Sapphire", "Fascinating"],
              rating: 4.66,
              uploadDate: Date()),
        MySvg(fileName: "greentree",
              thumbName: "greentree",
              author: "James Green",
              tags: ["Extraordinary", "Ruby", "Enchanting"],
              rating: 2.77,
              uploadDate: Date()),
        MySvg(fileName: "lightbulb",
              thumbName: "lightbulb",
              author: "Isabella Hall",
              tags: ["Astounding", "Emerald", "Mesmerizing"],
              rating: 6.53,
              uploadDate: Date()),
        MySvg(fileName: "lock",
              thumbName: "lock",
              author: "Benjamin Adams",
              tags: ["Breathtaking", "Topaz", "Delightful"],
              rating: 2.02,
              uploadDate: Date()),
        MySvg(fileName: "marketing",
              thumbName: "marketing",
              author: "Grace Hill",
              tags: ["Great", "Red", "Weird"],
              rating: 8.98,
              uploadDate: Date()),
        MySvg(fileName: "microsoft",
              thumbName: "microsoft",
              author: "Alexander Moore",
              tags: ["Awesome", "Blue", "Fun"],
              rating: 9.74,
              uploadDate: Date()),
        MySvg(fileName: "money-bag",
              thumbName: "money-bag",
              author: "Sofia Brooks",
              tags: ["Creative", "Yellow", "Exciting"],
              rating: 4.54,
              uploadDate: Date()),
        MySvg(fileName: "newstablet",
              thumbName: "newstablet",
              author: "Joseph Wright",
              tags: ["Amazing", "Green", "Cool"],
              rating: 4.40,
              uploadDate: Date()),
        MySvg(fileName: "newsvolume",
              thumbName: "newsvolume",
              author: "Chloe Davis",
              tags: ["Fantastic", "Purple", "Innovative"],
              rating: 9.09,
              uploadDate: Date()),
        MySvg(fileName: "noodle_logo",
              thumbName: "noodle_logo",
              author: "Daniel Martin",
              tags: ["Epic", "Orange", "Unique"],
              rating: 7.96,
              uploadDate: Date()),
        MySvg(fileName: "oldphone",
              thumbName: "oldphone",
              author: "Lily Young",
              tags: ["Excellent", "Pink", "Adventurous"],
              rating: 1.09,
              uploadDate: Date()),
        MySvg(fileName: "owl",
              thumbName: "owl",
              author: "Henry King",
              tags: ["Brilliant", "Teal", "Inspiring"],
              rating: 4.96,
        uploadDate: Date()),
        MySvg(fileName: "paperplane",
              thumbName: "paperplane",
              author: "Zoe Harris",
              tags: ["Magical", "Silver", "Mysterious"],
              rating: 9.92,
              uploadDate: Date()),
        MySvg(fileName: "plant",
              thumbName: "plant",
              author: "Samuel Garcia",
              tags: ["Spectacular", "Gold", "Energetic"],
              rating: 0.51,
              uploadDate: Date()),
        MySvg(fileName: "rabbit",
              thumbName: "rabbit",
              author: "John Doe",
              tags: ["Marvelous", "Cyan", "Vibrant"],
              rating: 4.52,
              uploadDate: Date()),
        MySvg(fileName: "rv",
              thumbName: "rv",
              author: "Jane Smith",
              tags: ["Wonderful", "Lime", "Playful"],
              rating: 7.11,
              uploadDate: Date()),
        MySvg(fileName: "sample_01",
              thumbName: "sample_01",
              author: "Alex Johnson",
              tags: ["Terrific", "Indigo", "Dynamic"],
              rating: 6.49,
              uploadDate: Date()),
        MySvg(fileName: "search",
              thumbName: "search",
              author: "David Wilson",
              tags: ["Phenomenal", "Amber", "Captivating"],
              rating: 1.18,
              uploadDate: Date()),
        MySvg(fileName: "sunset",
              thumbName: "sunset",
              author: "Emily Brown",
              tags: ["Outstanding", "Turquoise", "Imaginative"],
              rating: 8.26,
              uploadDate: Date()),
        MySvg(fileName: "target",
              thumbName: "target",
              author: "Michael Davis",
              tags: ["Impressive", "Magenta", "Whimsical"],
              rating: 0.23,
              uploadDate: Date()),
        MySvg(fileName: "umbrella",
              thumbName: "umbrella",
              author: "Olivia Taylor",
              tags: ["Stunning", "Sapphire", "Fascinating"],
              rating: 6.26,
              uploadDate: Date()),
    ]
}
