

import Foundation
import SwiftUI

class AppData
{
    static let instance = AppData()
    init () { }
    
    
    
    let searchFilter = SearchFilter(name: "Recent", imageName: "arrow.clockwise.circle.fill")
    
    
    
    
    
    
    let tempSvgs: [MySvg] = [
        MySvg(fileName: "calendar",
              thumbName: "calendar",
              author: "John Doe",
              tags: ["Great", "Red", "Weird"],
              rating: 5.24),
        MySvg(fileName: "acuarium",
              thumbName: "acuarium",
              author: "Jane Smith",
              tags: ["Awesome", "Blue", "Fun"],
              rating: 1.91),
        MySvg(fileName: "android",
              thumbName: "android",
              author: "Alex Johnson",
              tags: ["Creative", "Yellow", "Exciting"],
              rating: 9.13),
        MySvg(fileName: "bell",
              thumbName: "bell",
              author: "David Wilson",
              tags: ["Amazing", "Green", "Cool"],
              rating: 8.70),
        MySvg(fileName: "birthday-cake",
              thumbName: "birthday-cake",
              author: "Emily Brown",
              tags: ["Fantastic", "Purple", "Innovative"],
              rating: 8.18),
        MySvg(fileName: "butterfly",
              thumbName: "butterfly",
              author: "Michael Davis",
              tags: ["Epic", "Orange", "Unique"],
              rating: 6.87),
        MySvg(fileName: "camp",
              thumbName: "camp",
              author: "Olivia Taylor",
              tags: ["Excellent", "Pink", "Adventurous"],
              rating: 8.42),
        MySvg(fileName: "chat",
              thumbName: "chat",
              author: "Daniel Anderson",
              tags: ["Brilliant", "Teal", "Inspiring"],
              rating: 5.48),
        MySvg(fileName: "cow",
              thumbName: "cow",
              author: "Sophia Clark",
              tags: ["Magical", "Silver", "Mysterious"],
              rating: 8.35),
        MySvg(fileName: "diamond",
              thumbName: "diamond",
              author: "Matthew Martinez",
              tags: ["Spectacular", "Gold", "Energetic"],
              rating: 4.06),
        MySvg(fileName: "duck",
              thumbName: "duck",
              author: "Abigail Thompson",
              tags: ["Marvelous", "Cyan", "Vibrant"],
              rating: 9.58),
        MySvg(fileName: "employeebank",
              thumbName: "employeebank",
              author: "Jacob White",
              tags: ["Wonderful", "Lime", "Playful"],
              rating: 0.84),
        MySvg(fileName: "firecamp",
              thumbName: "firecamp",
              author: "Mia Lee",
              tags: ["Terrific", "Indigo", "Dynamic"],
              rating: 8.61),
        MySvg(fileName: "flower-bouquet",
              thumbName: "flower-bouquet",
              author: "Ethan Lewis",
              tags: ["Phenomenal", "Amber", "Captivating"],
              rating: 2.97),
        MySvg(fileName: "fox",
              thumbName: "fox",
              author: "Charlotte Turner",
              tags: ["Outstanding", "Turquoise", "Imaginative"],
              rating: 9.95),
        MySvg(fileName: "frog",
              thumbName: "frog",
              author: "William Walker",
              tags: ["Impressive", "Magenta", "Whimsical"],
              rating: 8.31),
        MySvg(fileName: "gift",
              thumbName: "gift",
              author: "Ava Rodriguez",
              tags: ["Stunning", "Sapphire", "Fascinating"],
              rating: 4.66),
        MySvg(fileName: "greentree",
              thumbName: "greentree",
              author: "James Green",
              tags: ["Extraordinary", "Ruby", "Enchanting"],
              rating: 2.77),
        MySvg(fileName: "lightbulb",
              thumbName: "lightbulb",
              author: "Isabella Hall",
              tags: ["Astounding", "Emerald", "Mesmerizing"],
              rating: 6.53),
        MySvg(fileName: "lock",
              thumbName: "lock",
              author: "Benjamin Adams",
              tags: ["Breathtaking", "Topaz", "Delightful"],
              rating: 2.02),
        MySvg(fileName: "marketing",
              thumbName: "marketing",
              author: "Grace Hill",
              tags: ["Great", "Red", "Weird"],
              rating: 8.98),
        MySvg(fileName: "microsoft",
              thumbName: "microsoft",
              author: "Alexander Moore",
              tags: ["Awesome", "Blue", "Fun"],
              rating: 9.74),
        MySvg(fileName: "money-bag",
              thumbName: "money-bag",
              author: "Sofia Brooks",
              tags: ["Creative", "Yellow", "Exciting"],
              rating: 4.54),
        MySvg(fileName: "newstablet",
              thumbName: "newstablet",
              author: "Joseph Wright",
              tags: ["Amazing", "Green", "Cool"],
              rating: 4.40),
        MySvg(fileName: "newsvolume",
              thumbName: "newsvolume",
              author: "Chloe Davis",
              tags: ["Fantastic", "Purple", "Innovative"],
              rating: 9.09),
        MySvg(fileName: "noodle_logo",
              thumbName: "noodle_logo",
              author: "Daniel Martin",
              tags: ["Epic", "Orange", "Unique"],
              rating: 7.96),
        MySvg(fileName: "oldphone",
              thumbName: "oldphone",
              author: "Lily Young",
              tags: ["Excellent", "Pink", "Adventurous"],
              rating: 1.09),
        MySvg(fileName: "owl",
              thumbName: "owl",
              author: "Henry King",
              tags: ["Brilliant", "Teal", "Inspiring"],
              rating: 4.96),
        MySvg(fileName: "paperplane",
              thumbName: "paperplane",
              author: "Zoe Harris",
              tags: ["Magical", "Silver", "Mysterious"],
              rating: 9.92),
        MySvg(fileName: "plant",
              thumbName: "plant",
              author: "Samuel Garcia",
              tags: ["Spectacular", "Gold", "Energetic"],
              rating: 0.51),
        MySvg(fileName: "rabbit",
              thumbName: "rabbit",
              author: "John Doe",
              tags: ["Marvelous", "Cyan", "Vibrant"],
              rating: 4.52),
        MySvg(fileName: "rv",
              thumbName: "rv",
              author: "Jane Smith",
              tags: ["Wonderful", "Lime", "Playful"],
              rating: 7.11),
        MySvg(fileName: "sample_01",
              thumbName: "sample_01",
              author: "Alex Johnson",
              tags: ["Terrific", "Indigo", "Dynamic"],
              rating: 6.49),
        MySvg(fileName: "search",
              thumbName: "search",
              author: "David Wilson",
              tags: ["Phenomenal", "Amber", "Captivating"],
              rating: 1.18),
        MySvg(fileName: "sunset",
              thumbName: "sunset",
              author: "Emily Brown",
              tags: ["Outstanding", "Turquoise", "Imaginative"],
              rating: 8.26),
        MySvg(fileName: "target",
              thumbName: "target",
              author: "Michael Davis",
              tags: ["Impressive", "Magenta", "Whimsical"],
              rating: 0.23),
        MySvg(fileName: "umbrella",
              thumbName: "umbrella",
              author: "Olivia Taylor",
              tags: ["Stunning", "Sapphire", "Fascinating"],
              rating: 6.26),
    ]
}
